plugins:
  eslint:
    enabled: true
    channel: eslint-5
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 300

exclude_patterns:
- spec/
- bin/
- static/
