version: '3.5'

services:
  web:
    image: shift-front-end-react
    build: .
    command: nodemon --legacy-watch --watch server server/server.js
    ports:
      - "3000:3000"
    entrypoint: ./bin/docker/yarn_entrypoint
    env_file: .env
    volumes:
      - .:/app
      - yarn_cache:/app/node_modules
    networks:
      - shift_net

volumes:
  yarn_cache:

networks:
  shift_net:
    driver: bridge
    name: shift_net
