version: '3'

services:
  web:
    image: shift-front-end-react
    build: .
    command: nodemon -w server.js
    ports:
      - "3000:3000"
    entrypoint: ./bin/docker/yarn_entrypoint
    env_file: .env
    volumes:
      - .:/app
      - yarn_cache:/app/node_modules

volumes:
  yarn_cache:
