version: 2.1
jobs:
  build:
    resource_class: large
    docker:
      - image: circleci/node:11.13.0
    environment:
      API_HOST: http://example.local
      API_HOST_PROXY: http://example.proxy.local
      NO_HTTPS: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - packages/reference/node_modules
            - packages/shift-next/node_modules
            - packages/shift-next-routes/node_modules
            - packages/shift-node-api/node_modules
            - packages/shift-react-components/node_modules
      - run:
          name: Create NextJS production build
          command: |
            yarn --cwd packages/reference build
            cat packages/reference/client/.next/BUILD_ID
      - save_cache:
          key: next-production-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - packages/reference/client/.next
  jest_test:
    resource_class: large
    docker:
      - image: circleci/node:11.13.0
    environment:
      API_HOST: http://example.local
      API_HOST_PROXY: http://example.proxy.local
      NO_HTTPS: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - packages/reference/node_modules
            - packages/shift-next/node_modules
            - packages/shift-next-routes/node_modules
            - packages/shift-node-api/node_modules
            - packages/shift-react-components/node_modules
      - run:
          name: Execute tests
          command: npx lerna run test --stream -- --silent
  cypress:
    resource_class: large
    docker:
      - image: callumbarratt/cypress:11.13.0
    parallelism: 4
    working_directory: /home/circleci/project
    steps:
      - checkout
      - restore_cache:
          name: Restore cache (Yarn)
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: Restore cache (NextJS build)
          key: next-production-build-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Install Cypress
          command: npx cypress verify
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/.cache/Cypress
            - node_modules
            - packages/reference/node_modules
            - packages/shift-next/node_modules
            - packages/shift-next-routes/node_modules
            - packages/shift-node-api/node_modules
            - packages/shift-react-components/node_modules
      - run:
          name: Start NextJS Server
          command: |
            pwd
            ls -la packages/reference/client
            cat packages/reference/client/.next/BUILD_ID
            yarn --cwd packages/reference start
          background: true
      - run:
          name: Wait-on http://localhost:3000
          command: npx wait-on http://localhost:3000
      - run:
          command: |
            TESTFILES=$(yarn run --silent cy:ci)
            cd packages/reference
            npx cypress run --spec $TESTFILES
      - store_artifacts:
          path: packages/reference/cypress/screenshots
      - store_artifacts:
          path: packages/reference/cypress/videos
    environment:
      - API_HOST: https://shift-platform-dev-api.global.ssl.fastly.net
      - API_HOST_PROXY: http://localhost:3000
      - NO_HTTPS: true
      - ENABLE_PAYPAL_LIVE_ENVIRONMENT: false
      - ENABLE_TEST_PAYPAL_BUTTON: true
  pwmetrics:
    docker:
      - image: circleci/node:11.13.0-browsers
    environment:
      API_HOST: https://shift-platform-dev-api.global.ssl.fastly.net
      API_HOST_PROXY: http://localhost:3000
      NO_HTTPS: true
      ENABLE_PAYPAL_LIVE_ENVIRONMENT: false
      ENABLE_TEST_PAYPAL_BUTTON: true
    steps:
      - checkout
      - restore_cache:
          name: Restore cache (Yarn)
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: Restore cache (NextJS build)
          key: next-production-build-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Start the server
          background: true
          command: |
            cat packages/reference/client/.next/BUILD_ID
            yarn --cwd packages/reference start
      - run:
          name: Start PW metrics
          command: |
            sleep 1
            yarn run pwmetrics --config=packages/reference/pwmetrics-config.js
  heroku_deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master

orbs:
  heroku: circleci/heroku@0.0.6

workflows:
  build_and_test:
    jobs:
      - build
      - jest_test
      - pwmetrics:
          requires:
            - build
      - cypress:
          requires:
            - build
      # - heroku_deploy:
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     requires:
      #       - jest_test
      #       - pwmetrics_test
      #       - cypress_build
      #       - cypress_run
