version: 2.1
jobs:
  build:
    resource_class: large
    docker:
      - image: circleci/node:11.13.0
    environment:
      API_HOST: http://example.local
      API_HOST_PROXY: http://example.proxy.local
      NO_HTTPS: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - packages/reference/node_modules
            - packages/shift-next/node_modules
            - packages/shift-next-routes/node_modules
            - packages/shift-node-api/node_modules
            - packages/shift-react-components/node_modules
      - run:
          name: Create NextJS production build
          command: |
            yarn --cwd packages/reference build
            cat packages/reference/client/.next/BUILD_ID
      - save_cache:
          key: next-production-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - packages/reference/client/.next
  jest_test:
    resource_class: large
    docker:
      - image: circleci/node:11.13.0
    environment:
      API_HOST: http://example.local
      API_HOST_PROXY: http://example.proxy.local
      NO_HTTPS: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - packages/reference/node_modules
            - packages/shift-next/node_modules
            - packages/shift-next-routes/node_modules
            - packages/shift-node-api/node_modules
            - packages/shift-react-components/node_modules
      - run:
          name: Execute tests
          command: npx lerna run test --stream -- --silent
  pwmetrics_test:
    docker:
      - image: circleci/node:11.13.0-browsers
    environment:
      API_HOST: https://shift-platform-dev-api.global.ssl.fastly.net
      API_HOST_PROXY: http://localhost:3000
      NO_HTTPS: true
      ENABLE_PAYPAL_LIVE_ENVIRONMENT: false
      ENABLE_TEST_PAYPAL_BUTTON: true
    steps:
      - checkout
      - restore_cache:
          name: Restore cache (Yarn)
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: Restore cache (NextJS build)
          key: next-production-build-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Start the server
          background: true
          command: |
            cat packages/reference/client/.next/BUILD_ID
            yarn --cwd packages/reference start
      - run:
          name: Start PW metrics
          command: |
            sleep 1
            yarn run pwmetrics --config=packages/reference/pwmetrics-config.js
  heroku_deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master

orbs:
  cypress: cypress-io/cypress@1.7.0
  heroku: circleci/heroku@0.0.6

executors:
  cypress-node-11:
    resource_class: large
    docker:
      - image: 'callumbarratt/cypress:11.13.0'
    environment:
      API_HOST: https://shift-platform-dev-api.global.ssl.fastly.net
      API_HOST_PROXY: http://localhost:3000
      NO_HTTPS: true
      ENABLE_PAYPAL_LIVE_ENVIRONMENT: false
      ENABLE_TEST_PAYPAL_BUTTON: true

workflows:
  build_and_test:
    jobs:
      - build
      - jest_test
      - pwmetrics_test:
          requires:
            - build
      - cypress/run:
          name: cypress_run
          pre-steps:
            - checkout
            - restore_cache:
                name: Restore cache (Yarn)
                key: yarn-dependencies-{{ checksum "yarn.lock" }}
            - restore_cache:
                name: Restore cache (NextJS build)
                key: next-production-build-{{ .Branch }}-{{ .Revision }}
            - run:
                name: Install Dependencies
                command: yarn install --frozen-lockfile
          post-steps:
            - store_artifacts:
                path: packages/reference/cypress/screenshots
            - store_artifacts:
                path: packages/reference/cypress/videos
          parallelism: 4
          requires:
            - build
          no-workspace: true
          executor: cypress-node-11
          yarn: true
          start: yarn --cwd packages/reference start
          parallel: true # Specify we are using parallelism so it uses the shared workspace output from cypress/install (NextJS build)
          group: All Integration tests
          wait-on: 'http://localhost:3000'
          command: |
            TESTFILES=$(yarn run --silent cy:ci)
            cd packages/reference
            npx cypress run --spec $TESTFILES
      # - heroku_deploy:
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     requires:
      #       - jest_test
      #       - pwmetrics_test
      #       - cypress_build
      #       - cypress_run
