// Action types
export const SET_PROCESS_LOADING = 'SET_PROCESS_LOADING'
export const SET_PROCESS_ERRORED = 'SET_PROCESS_ERRORED'
export const RESET_PROCESSES = 'RESET_PROCESSES'
export const SET_PRODUCT = 'SET_PRODUCT'
export const UPDATE_CART_LINE_ITEMS = 'UPDATE_CART_LINE_ITEMS'
export const STORE_CART = 'STORE_CART'
